// Generated by CoffeeScript 1.7.1
(function() {
  var Let, defineInBulk, defineOneVariable, env, resetEnv, vars;

  env = {};

  vars = {};

  resetEnv = function() {
    var name, _i, _len, _ref, _results;
    vars = {};
    _ref = Object.keys(env);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      if (name !== 'Let') {
        _results.push(delete env[name]);
      }
    }
    return _results;
  };

  defineOneVariable = function(name, thing) {
    if (name === 'Let') {
      throw 'cannot redefine Let';
    }
    if (typeof thing === 'function') {
      vars[name] = thing.bind(env);
    } else {
      vars[name] = function() {
        return thing;
      };
    }
    return Object.defineProperty(env, name, {
      get: function() {
        return vars[name]();
      },
      configurable: true,
      enumerable: true
    });
  };

  defineInBulk = function(object, preserve) {
    var name, thing, _results;
    if (preserve == null) {
      preserve = false;
    }
    if (!preserve) {
      resetEnv();
    }
    _results = [];
    for (name in object) {
      thing = object[name];
      _results.push(defineOneVariable(name, thing));
    }
    return _results;
  };

  Let = function() {
    var args, name, thing;
    args = [].slice.apply(arguments);
    if (typeof args[0] === 'object') {
      return defineInBulk(args[0]);
    } else {
      name = args[0], thing = args[1];
      return defineOneVariable(name, thing);
    }
  };

  Let.preserve = function(object) {
    return defineInBulk(object, true);
  };

  Let.clear = function() {
    return resetEnv();
  };

  Object.defineProperty(env, 'Let', {
    writable: false,
    configurable: false,
    value: Let
  });

  (typeof module !== "undefined" && module !== null ? module.exports = env : void 0) || (this.env = env);

}).call(this);
